version: "3.7"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - front-network
networks:
  front-network:
    driver: bridge
